version: "3.8"
services:
  web:
    build: .
    image: meetbariya/studybuddy:1.0
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
    entrypoint: /opt/venv/bin/python manage.py runserver 0.0.0.0:8000
    # command: "/opt/venv/bin/gunicorn config.wsgi:application --bind '0.0.0.0:8000'"
  # nginx:
  #   image: nginx:1.25-alpine
  #   ports: 
  #     - "80:80"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d:rw
volumes:
  staticfiles: